# Generated by Django 3.2.6 on 2021-08-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='H_or_X',
            new_name='nosoz',
        ),
    ]
