# Generated by Django 3.2.6 on 2021-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugat', '0002_rename_h_or_x_nosoz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soz',
            name='correct',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
