# Generated by Django 3.2.6 on 2021-08-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugat', '0003_alter_soz_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soz',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
